networks:
  search-net:
    driver: proxy
volumes:
  opensearch-data1:
  
services:
  opensearch:
    image: opensearchproject/opensearch:3@sha256:798cf28e226a32f5c928dd1ed9478dd3a33d2212176aad3679020088ad3afa1a
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123849password!P
    ports:
      - "9200:9200"
    networks:
      - proxy
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
