networks:
  search-net:
    driver: proxy
volumes:
  opensearch-data1:
  
services:
  opensearch:
    image: opensearchproject/opensearch:3@sha256:1647ce2e07371f1ac8bbad28890a64ef77c5a694a61f656120f0ace09e66bf48
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=123849password!P
    ports:
      - "9200:9200"
    networks:
      - proxy
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
